    /*
     * Read-only data
     */

    .section .rodata
    .align 2

EXPF_T:
    .word 0x3F800000, 0x3F8058D8, 0x3F80B1ED, 0x3F810B41
    .word 0x3F8164D2, 0x3F81BEA1, 0x3F8218AF, 0x3F8272FC
    .word 0x3F82CD87, 0x3F832850, 0x3F838359, 0x3F83DEA1
    .word 0x3F843A29, 0x3F8495F0, 0x3F84F1F6, 0x3F854E3D
    .word 0x3F85AAC3, 0x3F86078A, 0x3F866491, 0x3F86C1D9
    .word 0x3F871F62, 0x3F877D2B, 0x3F87DB35, 0x3F883981
    .word 0x3F88980F, 0x3F88F6DD, 0x3F8955EE, 0x3F89B541
    .word 0x3F8A14D5, 0x3F8A74AD, 0x3F8AD4C6, 0x3F8B3523
    .word 0x3F8B95C2, 0x3F8BF6A4, 0x3F8C57CA, 0x3F8CB933
    .word 0x3F8D1ADF, 0x3F8D7CD0, 0x3F8DDF04, 0x3F8E417D
    .word 0x3F8EA43A, 0x3F8F073B, 0x3F8F6A81, 0x3F8FCE0C
    .word 0x3F9031DC, 0x3F9095F2, 0x3F90FA4D, 0x3F915EED
    .word 0x3F91C3D3, 0x3F922900, 0x3F928E72, 0x3F92F42C
    .word 0x3F935A2B, 0x3F93C072, 0x3F9426FF, 0x3F948DD4
    .word 0x3F94F4F0, 0x3F955C53, 0x3F95C3FF, 0x3F962BF2
    .word 0x3F96942D, 0x3F96FCB1, 0x3F97657D, 0x3F97CE92
    .word 0x3F9837F0, 0x3F98A197, 0x3F990B88, 0x3F9975C2
    .word 0x3F99E046, 0x3F9A4B13, 0x3F9AB62B, 0x3F9B218D
    .word 0x3F9B8D3A, 0x3F9BF931, 0x3F9C6573, 0x3F9CD201
    .word 0x3F9D3EDA, 0x3F9DABFE, 0x3F9E196E, 0x3F9E872A
    .word 0x3F9EF532, 0x3F9F6387, 0x3F9FD228, 0x3FA04116
    .word 0x3FA0B051, 0x3FA11FD9, 0x3FA18FAF, 0x3FA1FFD2
    .word 0x3FA27043, 0x3FA2E102, 0x3FA3520F, 0x3FA3C36B
    .word 0x3FA43516, 0x3FA4A70F, 0x3FA51958, 0x3FA58BEF
    .word 0x3FA5FED7, 0x3FA6720E, 0x3FA6E595, 0x3FA7596C
    .word 0x3FA7CD94, 0x3FA8420C, 0x3FA8B6D5, 0x3FA92BEF
    .word 0x3FA9A15B, 0x3FAA1718, 0x3FAA8D26, 0x3FAB0387
    .word 0x3FAB7A3A, 0x3FABF13F, 0x3FAC6897, 0x3FACE041
    .word 0x3FAD583F, 0x3FADD090, 0x3FAE4934, 0x3FAEC22D
    .word 0x3FAF3B79, 0x3FAFB519, 0x3FB02F0E, 0x3FB0A957
    .word 0x3FB123F6, 0x3FB19EE9, 0x3FB21A32, 0x3FB295D0
    .word 0x3FB311C4, 0x3FB38E0E, 0x3FB40AAF, 0x3FB487A6
    .word 0x3FB504F3, 0x3FB58298, 0x3FB60094, 0x3FB67EE7
    .word 0x3FB6FD92, 0x3FB77C95, 0x3FB7FBF0, 0x3FB87BA3
    .word 0x3FB8FBAF, 0x3FB97C14, 0x3FB9FCD2, 0x3FBA7DEA
    .word 0x3FBAFF5B, 0x3FBB8126, 0x3FBC034A, 0x3FBC85CA
    .word 0x3FBD08A4, 0x3FBD8BD8, 0x3FBE0F68, 0x3FBE9353
    .word 0x3FBF179A, 0x3FBF9C3C, 0x3FC0213B, 0x3FC0A695
    .word 0x3FC12C4D, 0x3FC1B261, 0x3FC238D2, 0x3FC2BFA1
    .word 0x3FC346CD, 0x3FC3CE57, 0x3FC4563F, 0x3FC4DE85
    .word 0x3FC5672A, 0x3FC5F02E, 0x3FC67991, 0x3FC70353
    .word 0x3FC78D75, 0x3FC817F7, 0x3FC8A2D8, 0x3FC92E1B
    .word 0x3FC9B9BE, 0x3FCA45C1, 0x3FCAD226, 0x3FCB5EED
    .word 0x3FCBEC15, 0x3FCC799F, 0x3FCD078C, 0x3FCD95DA
    .word 0x3FCE248C, 0x3FCEB3A1, 0x3FCF4319, 0x3FCFD2F4
    .word 0x3FD06334, 0x3FD0F3D7, 0x3FD184DF, 0x3FD2164C
    .word 0x3FD2A81E, 0x3FD33A54, 0x3FD3CCF1, 0x3FD45FF3
    .word 0x3FD4F35B, 0x3FD58729, 0x3FD61B5E, 0x3FD6AFFA
    .word 0x3FD744FD, 0x3FD7DA67, 0x3FD87039, 0x3FD90673
    .word 0x3FD99D16, 0x3FDA3421, 0x3FDACB94, 0x3FDB6371
    .word 0x3FDBFBB8, 0x3FDC9468, 0x3FDD2D82, 0x3FDDC706
    .word 0x3FDE60F5, 0x3FDEFB4E, 0x3FDF9613, 0x3FE03143
    .word 0x3FE0CCDF, 0x3FE168E7, 0x3FE2055B, 0x3FE2A23C
    .word 0x3FE33F89, 0x3FE3DD44, 0x3FE47B6D, 0x3FE51A03
    .word 0x3FE5B907, 0x3FE65879, 0x3FE6F85B, 0x3FE798AB
    .word 0x3FE8396A, 0x3FE8DA99, 0x3FE97C38, 0x3FEA1E47
    .word 0x3FEAC0C7, 0x3FEB63B7, 0x3FEC0719, 0x3FECAAEC
    .word 0x3FED4F30, 0x3FEDF3E7, 0x3FEE9910, 0x3FEF3EAB
    .word 0x3FEFE4BA, 0x3FF08B3B, 0x3FF13231, 0x3FF1D99A
    .word 0x3FF28177, 0x3FF329C9, 0x3FF3D290, 0x3FF47BCC
    .word 0x3FF5257D, 0x3FF5CFA4, 0x3FF67A41, 0x3FF72555
    .word 0x3FF7D0DF, 0x3FF87CE1, 0x3FF9295A, 0x3FF9D64A
    .word 0x3FFA83B3, 0x3FFB3194, 0x3FFBDFED, 0x3FFC8EC0
    .word 0x3FFD3E0C, 0x3FFDEDD2, 0x3FFE9E11, 0x3FFF4ECB

UPPER_BOUND:
    .word 0x42B17218

LOWER_BOUND:
    .word 0xC2CFF1B5

INV_LN2N_HI:
    .word 0x43B8AA3B

INV_LN2N_LO:
    .word 0x36A57060

LN2N_HI:
    .word 0x3B317218

LN2N_LO:
    .word 0xAD02E308

EXPF_Q:
    .word 0x3F800000, 0x3F000000, 0x3E2AAAAC, 0x3D2AAAA6

    /*
     * Code
     */

    .section .text
    .align 2

    .global re_expf_asm
    .type   re_expf_asm, @function

re_expf_asm:

    /*
     * Below are the Pseudo Instructions used.
     * They expand into one instruction, so do not affect the cycle count.
     * - j LABEL
     *      jal zero, LABEL
     * - bnez rs, LABEL
     *      bne rs, zero, LABEL
     */

    /* 
     * The input function argument is written to register fa0 as per the ABI 
     * Thus, fa0 holds the input x
     */

    /* Classify the input */
    fclass.s    a0, fa0                 /* Categorise the input and set the bit accordingly */

    /* Load INV_LN2N_HI */
.Laddr1:
    auipc   a2,  %pcrel_hi(INV_LN2N_HI) /* Load the upper 20 bits of the address */
    flw     fa2, %pcrel_lo(.Laddr1)(a2) /* Load the value using the lower 12 bits as offset */

    /* Load INV_LN2N_LO */
.Laddr2:
    auipc   a3,  %pcrel_hi(INV_LN2N_LO) /* Load the upper 20 bits of the address */
    flw     fa3, %pcrel_lo(.Laddr2)(a3) /* Load the value using the lower 12 bits as offset */

    /* Check if it is a special number */
    andi    a1, a0, 0x399               /* Check if special case bits are set */
    bnez    a1, .Lspecial               /* Branch if bits are set */

    /* Multiply to get high part */
    fmul.s  fa1, fa0, fa2               /* Multiply x and INV_LN2N_HI */

    /* Load UPPER_BOUND */
.Laddr3:
    auipc   a4,  %pcrel_hi(UPPER_BOUND) /* Load the upper 20 bits of the address */
    flw     fa4, %pcrel_lo(.Laddr3)(a4) /* Load the value using the lower 12 bits as offset */

    /* Fused-Multiply-Subtract to get low part */
    fmsub.s fa2, fa0, fa2, fa1          /* FMSUB(x, INV_LN2N_HI, high) */

    /* Load LOWER_BOUND */
.Laddr4:
    auipc   a5,  %pcrel_hi(LOWER_BOUND) /* Load the upper 20 bits of the address */
    flw     fa5, %pcrel_lo(.Laddr4)(a5) /* Load the value using the lower 12 bits as offset */

    /* Fused-Multiply-Add to get tail part */
    fmadd.s fa2, fa0, fa3, fa2          /* FMADD(x, INV_LN2N_LO, low) */

    /* Set flags based on BOUND */
    flt.s   a1, fa4, fa0                /* Check if x > UPPER_BOUND */
    flt.s   a2, fa0, fa5                /* Check if x < LOWER_BOUND */

    /* Add to get transformed input */
    fadd.s  fa1, fa1, fa2               /* Add high and tail */

    /* Branch based on BOUND */
    bnez    a1, .Lret_inf_p             /* Branch if x > UPPER_BOUND */
    bnez    a2, .Lret_zero              /* Branch if x < LOWER_BOUND */

    /* Load LN2N_HI */
.Laddr5:
    auipc   a3,  %pcrel_hi(LN2N_HI)     /* Load the upper 20 bits of the address */
    flw     fa3, %pcrel_lo(.Laddr5)(a3) /* Load the value using the lower 12 bits as offset */

    /* Extract Integer Part */
    fcvt.w.s    a1,  fa1                /* Get the nearest integer (k) from the float */

    /* Load LN2N_LO */
.Laddr6:
    auipc   a4,  %pcrel_hi(LN2N_LO)     /* Load the upper 20 bits of the address */
    flw     fa4, %pcrel_lo(.Laddr6)(a4) /* Load the value using the lower 12 bits as offset */

    /* Convert Integer Part to FP Represntation */
    fcvt.s.w    fa5, a1                 /* Convert the integer to float representation (kf) */

    /* Load address of Polynomial Coefficients */
.Laddr7:
    auipc   a2, %pcrel_hi(EXPF_Q)       /* Load the upper 20 bits of the address */
    addi    a2, a2, %pcrel_lo(.Laddr7)  /* Load the lower 12 bits of the address */

    /* Extract low bits of Fractional Part */
    fnmsub.s    fa1, fa5, fa3, fa0      /* FNMSUB(kf, LN2N_HI, x) */

    /* Load EXPF_Q[0] and EXPF_Q[1] */
    flw     fa2, 0(a2)                  /* Load EXPF_Q[0] */
    flw     fa3, 4(a2)                  /* Load EXPF_Q[1] */

    /* Extract Fractional Part */
    fnmsub.s    fa1, fa5, fa4, fa1      /* FNMSUB(kf, LN2N_LO, r) */

    /* Load EXPF_Q[2] and EXPF_Q[3] */
    flw     fa4, 8(a2)                  /* Load EXPF_Q[2] */
    flw     fa5, 12(a2)                 /* Load EXPF_Q[3] */

    /* Evaluate r^2 */
    fmul.S  ft2, fa1, fa1               /* Multiply r with r */

    /* Evaluate r^1 part */
    fmadd.s ft1, fa3, fa1, fa2          /* FMADD(EXPF_Q[1], r, EXPF_Q[0]) */

    /* Evaluate r^3 part */
    fmadd.s ft3, fa5, fa1, fa4          /* FMADD(EXPF_Q[3], r, EXPF_Q[2]) */

    /* Load address of EXPF_T */
.Laddr8:
    auipc   a2, %pcrel_hi(EXPF_T)       /* Load the upper 20 bits of the address */
    addi    a2, a2, %pcrel_lo(.Laddr8)  /* Load the lower 12 bits of the address */

    /* Evaluate final polynomial */
    fmadd.s fa2, ft3, ft2, ft1          /* FMADD(r3, r^2, r1) */

    /* Calculate EXPF_T index offset */
    andi    a3, a1, 0x0FF               /* Calculate i = k mod N = k & (N-1) */
    slli    a3, a3, 2                   /* Multiply i by 4 to calculate offset */

    /* Calculate tail */
    fmul.s  fa2, fa1, fa2               /* Multiply r and q */

    /* Load EXPF_T[i] */
    add     a2,  a2, a3                 /* Add offset to table address */
    flw     fa3, 0(a2)                  /* Load EXPF_T[i] */

    /* Calculate intermediate */
    fmadd.s fa1, fa2, fa3, fa3          /* FMADD(tail, EXPF_T[i], EXPF_T[i]) */

    /* Build Exponent Bit Mask */
    lui     a0, 0x80800                 /* Build upper 20 bits of mask */
    addi    a0, a0, -1                  /* Update lower 12 bits of mask */

    /* Update exponent bits */
    fmv.x.w a2,  fa1                    /* Move intermediate to integer register */
    srai    a1,  a1, 8                  /* Calculate j = k / N */
    srli    a3,  a2, 23                 /* Shift out mantissa bits */
    add     a3,  a3, a1                 /* Add increment j to exponent bits */
    andi    a3,  a3, 0x0FF              /* Mask to retain only the exponent bits */
    slli    a3,  a3, 23                 /* Shift exponent bits back into position */
    and     a2,  a2, a0                 /* Remove the exponent bits using the mask */
    or      a2,  a2, a3                 /* Include new exponent bits */
    fmv.w.x fa0, a2                     /* Move the bits back into float register */

.Ldone:

    ret

.Lspecial:

    /* Check NaN */
    andi a1, a0, 0x300                  /* Check if bits corresponding to NaN are set */
    bnez a1, .Lret_nan                  /* Branch if bits are set */

    /* Check Zero */
    andi a1, a0, 0x018                  /* Check if bits corresponding to zero are set */
    bnez a1, .Lret_one                  /* Branch if bits are set */

    /* Check +Inf */
    andi a1, a0, 0x080                  /* Check if bits corresponding to +Inf are set */
    bnez a1, .Ldone                     /* Branch if bits are set */

    /* Check -Inf */
    andi a1, a0, 0x001                  /* Check if bits corresponding to -Inf are set */
    bnez a1, .Lret_zero                 /* Branch if bits are set */

.Lret_nan:
    fadd.s  fa0, fa0, fa0               /* Add for NaN */
    j       .Ldone

.Lret_inf_p:

    lui     a1,  0x7F800                /* Load bits for +Inf */
    fmv.w.x fa0, a1                     /* Move to float register */
    j       .Ldone

.Lret_zero:

    fcvt.s.w    fa0, zero               /* Move zero to float register */
    j           .Ldone

.Lret_one:

    addi        a1,  zero, 1            /* Load integer 1 */
    fcvt.s.w    fa0, a1                 /* Convert 1 to float representation */
    j           .Ldone

    .size re_expf_asm, .-re_expf_asm